/** English UI strings (no translation layer). */
export const strings: Record<string, string> = {
  nav_home:      'Home',
  nav_guide:     'Guide',
  nav_forecast:  'Forecast',
  nav_compare:   'Compare',
  nav_search:    'Search',
  nav_favorites: 'Favorites',
  nav_settings:  'Settings',
  preferences:                    'Preferences',
  settings_title:                 'Settings',
  settings_subtitle:              'Customise your MyAirSafe experience.',
  settings_general:               'General',
  settings_notifications:         'Air Quality Alerts',
  settings_notifications_desc:    'Get notified when air quality changes in your area',
  settings_units:                 'Measurement Units',
  settings_units_desc:            'Choose your preferred unit system',
  settings_save:                  'Save Changes',
  settings_saved:                 'Saved!',
  settings_reset:                 'Reset Defaults',
  settings_metric:                'Metric',
  settings_imperial:              'Imperial',
  settings_senior_title:          'Designed for Senior Wellbeing',
  settings_senior_desc:           'MyAirSafe uses clear text, high contrast colours, and elder-focused health guidance throughout.',
  settings_info:                  'Settings are saved locally in your browser.',
  notif_enabled:                  'Alerts enabled. You\'ll be notified when air quality is poor.',
  notif_denied:                   'Notification permission denied. Please enable it in your browser settings.',
  notif_unsupported:              'Your browser does not support notifications.',
  fav_title:          'My Favourites',
  fav_subtitle:       'Saved Stations',
  fav_empty_title:    'No favourites yet',
  fav_empty_desc:     'Search for stations you visit often and save them here for quick access.',
  fav_add:            'Add Location',
  fav_browse:         'Browse Locations',
  fav_saved_one:      'saved location',
  fav_saved_many:     'saved locations',
  status_good:            'Good',
  status_moderate:        'Moderate',
  status_unhealthy:       'Unhealthy',
  status_very_unhealthy:  'Very Unhealthy',
  status_hazardous:       'Hazardous',
}
